Repository redhat-cop/rego-policies, pull requests merged in 2020-07, with the labels that each got.

#63 Added check for memory resources which are template params
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-Deployment.yml
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-DeploymentConfig.yml
  policy/warn-k8s_ocp-deployment_deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/L

#72 Updated action back to central redhat-cop
  .github/workflows/conftest.yaml
Labels: approved, lgtm, size/XS

#74 Added check for cpu resources which are template params
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-Deployment.yml
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-DeploymentConfig.yml
  policy/warn-k8s_ocp-deployment_deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/S

#75 Added bats-lib methods
  .gitignore
  _test/_helpers.bash
  _test/bats-support-clone.bash
  _test/conftest.sh
Labels: approved, lgtm, size/L

#83 Simplified combine unit test criteria
  policy/combine/deployment-has-matching-poddisruptionbudget/test_data/unit/list.yml
  policy/combine/deployment-has-matching-pvc/test_data/unit/list.yml
  policy/combine/deployment-has-matching-service/test_data/unit/list.yml
  policy/combine/deployment-has-matching-serviceaccount/test_data/unit/list.yml
  policy/combine/namespace-has-networkpolicy/test_data/unit/list.yml
  policy/combine/service-has-matching-servicenonitor/test_data/unit/list.yml
Labels: approved, size/M

#82 Updated gatekeeper deploy to only validate non control based namespaces
  TESTING.md
  _test/conftest-unittests.sh
  _test/deploy-gatekeeper.sh
  _test/gatekeeper-integrationtests.sh
  _test/namespace-under-test.yml
  gatekeeper/gatekeeper-template-manager.yml
Labels: approved, lgtm, size/L

#86 Updated docs to fix ci
  POLICIES.md
Labels: approved, lgtm, size/L

#87 Added readme's into each policy dir to explain them abit more
  policy/combine/README.md
  policy/ocp/bestpractices/README.md
  policy/ocp/deprecated/README.md
  policy/podman/README.md
Labels: approved, lgtm, size/S

#85 Added validation step for integration data
  .github/workflows/conftest.yaml
Labels: approved, lgtm, size/XS

#79 🦅 ADD - Cansu to be able to review and merge 🦅
  OWNERS
Labels: approved, lgtm, size/XS

#84 Converted combine tests to use gatekeeper cache
  .github/workflows/conftest.yaml
  .gitignore
  POLICIES.md
  _test/all-namespaces/ocp/bestpractices/all.yml
  _test/conftest-unittests.sh
  _test/deploy-gatekeeper.sh
  _test/gatekeeper-integrationtests.sh
  gatekeeper/config.yml
  policy/combine/deployment-has-matching-poddisruptionbudget/src.rego
  policy/combine/deployment-has-matching-poddisruptionbudget/test_data/unit/list.yml
  policy/combine/deployment-has-matching-pvc/src.rego
  policy/combine/deployment-has-matching-pvc/test_data/unit/list.yml
  policy/combine/deployment-has-matching-service/src.rego
  policy/combine/deployment-has-matching-service/test_data/unit/list.yml
  policy/combine/deployment-has-matching-serviceaccount/src.rego
  policy/combine/deployment-has-matching-serviceaccount/test_data/unit/list.yml
  policy/combine/namespace-has-networkpolicy/src.rego
  policy/combine/service-has-matching-servicenonitor/src.rego
  policy/combine/service-has-matching-servicenonitor/test_data/unit/list.yml
  policy/ocp/bestpractices/container-volumemount-missing/test_data/integration/list.yml
  policy/ocp/requiresinventory/README.md
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-pvc/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-pvc/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-service/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-service/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/test_data/integration/list.yml
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/src.rego
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/test_data/integration/list.yml
Labels: approved, lgtm, size/XXL

#90 Split out the docs ci bits into its own pipeline
  .github/workflows/conftest.yaml
  .github/workflows/docs.yaml
  README.md
Labels: approved, lgtm, size/M

#91 Updated kinds annotation to be lower case
  policy/combine/namespace-has-networkpolicy/src.rego
  policy/ocp/bestpractices/common-k8s-labels-notset/src.rego
  policy/ocp/bestpractices/container-env-maxmemory-notset/src.rego
  policy/ocp/bestpractices/container-image-latest/src.rego
  policy/ocp/bestpractices/container-java-xmx-set/src.rego
  policy/ocp/bestpractices/container-labelkey-inconsistent/src.rego
  policy/ocp/bestpractices/container-liveness-readinessprobe-equal/src.rego
  policy/ocp/bestpractices/container-livenessprobe-notset/src.rego
  policy/ocp/bestpractices/container-readinessprobe-notset/src.rego
  policy/ocp/bestpractices/container-resources-limits-cpu-set/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-notset/src.rego
  policy/ocp/bestpractices/container-resources-memoryunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-cpuunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-secret-mounted-envs/src.rego
  policy/ocp/bestpractices/container-volumemount-inconsistent-path/src.rego
  policy/ocp/bestpractices/container-volumemount-missing/src.rego
  policy/ocp/bestpractices/deploymentconfig-triggers-notset/src.rego
  policy/ocp/bestpractices/pod-hostnetwork/src.rego
  policy/ocp/bestpractices/pod-replicas-below-one/src.rego
  policy/ocp/bestpractices/pod-replicas-not-odd/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-apigroup-notset/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-kind-notset/src.rego
  policy/ocp/deprecated/3_11/buildconfig-v1/src.rego
  policy/ocp/deprecated/3_11/deploymentconfig-v1/src.rego
  policy/ocp/deprecated/3_11/imagestream-v1/src.rego
  policy/ocp/deprecated/3_11/projectrequest-v1/src.rego
  policy/ocp/deprecated/3_11/rolebinding-v1/src.rego
  policy/ocp/deprecated/3_11/route-v1/src.rego
  policy/ocp/deprecated/3_11/securitycontextconstraints-v1/src.rego
  policy/ocp/deprecated/3_11/template-v1/src.rego
  policy/ocp/deprecated/4_1/buildconfig-custom-strategy/src.rego
  policy/ocp/deprecated/4_2/authorization-openshift/src.rego
  policy/ocp/deprecated/4_2/automationbroker-v1alpha1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v2/src.rego
  policy/ocp/deprecated/4_2/operatorsources-v1/src.rego
  policy/ocp/deprecated/4_2/osb-v1/src.rego
  policy/ocp/deprecated/4_2/servicecatalog-v1beta1/src.rego
  policy/ocp/deprecated/4_3/buildconfig-jenkinspipeline-strategy/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-pvc/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-service/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/src.rego
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/src.rego
  policy/podman/history/contains-layer/src.rego
  policy/podman/images/image-size-not-greater-than/src.rego
Labels: approved, lgtm, size/M

#92 Upgraded to beta11 of gatekeeper
  _test/deploy-gatekeeper.sh
  gatekeeper/config.yml
Labels: approved, lgtm, size/S

#93 Added version to expected labels
  _test/all-namespaces/ocp/bestpractices/all.yml
  policy/ocp/bestpractices/common-k8s-labels-notset/src.rego
  policy/ocp/bestpractices/common-k8s-labels-notset/test_data/integration/list.yml
  policy/ocp/bestpractices/container-env-maxmemory-notset/test_data/integration/list.yml
  policy/ocp/bestpractices/container-image-latest/test_data/integration/list.yml
  policy/ocp/bestpractices/container-java-xmx-set/test_data/integration/list.yml
  policy/ocp/bestpractices/container-labelkey-inconsistent/test_data/integration/list.yml
  policy/ocp/bestpractices/container-liveness-readinessprobe-equal/test_data/integration/list.yml
  policy/ocp/bestpractices/container-livenessprobe-notset/test_data/integration/list.yml
  policy/ocp/bestpractices/container-readinessprobe-notset/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-limits-cpu-set/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-limits-memory-greater-than/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-limits-memory-notset/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-memoryunit-incorrect/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-requests-cpuunit-incorrect/test_data/integration/list.yml
  policy/ocp/bestpractices/container-resources-requests-memory-greater-than/test_data/integration/list.yml
  policy/ocp/bestpractices/container-secret-mounted-envs/test_data/integration/list.yml
  policy/ocp/bestpractices/container-volumemount-inconsistent-path/test_data/integration/list.yml
  policy/ocp/bestpractices/container-volumemount-missing/test_data/integration/list.yml
  policy/ocp/bestpractices/pod-hostnetwork/test_data/integration/list.yml
  policy/ocp/bestpractices/pod-replicas-below-one/test_data/integration/list.yml
  policy/ocp/bestpractices/pod-replicas-not-odd/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-pvc/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-service/test_data/integration/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/test_data/integration/list.yml
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/test_data/integration/list.yml
Labels: approved, lgtm, size/L

#94 Fixed docs not being upto date
  .github/workflows/docs.yaml
  POLICIES.md
  README.md
  policy/combine/namespace-has-networkpolicy/src.rego
  policy/ocp/bestpractices/common-k8s-labels-notset/src.rego
  policy/ocp/bestpractices/container-env-maxmemory-notset/src.rego
  policy/ocp/bestpractices/container-image-latest/src.rego
  policy/ocp/bestpractices/container-java-xmx-set/src.rego
  policy/ocp/bestpractices/container-labelkey-inconsistent/src.rego
  policy/ocp/bestpractices/container-liveness-readinessprobe-equal/src.rego
  policy/ocp/bestpractices/container-livenessprobe-notset/src.rego
  policy/ocp/bestpractices/container-readinessprobe-notset/src.rego
  policy/ocp/bestpractices/container-resources-limits-cpu-set/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-notset/src.rego
  policy/ocp/bestpractices/container-resources-memoryunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-cpuunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-secret-mounted-envs/src.rego
  policy/ocp/bestpractices/container-volumemount-inconsistent-path/src.rego
  policy/ocp/bestpractices/container-volumemount-missing/src.rego
  policy/ocp/bestpractices/deploymentconfig-triggers-notset/src.rego
  policy/ocp/bestpractices/pod-hostnetwork/src.rego
  policy/ocp/bestpractices/pod-replicas-below-one/src.rego
  policy/ocp/bestpractices/pod-replicas-not-odd/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-apigroup-notset/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-kind-notset/src.rego
  policy/ocp/deprecated/3_11/buildconfig-v1/src.rego
  policy/ocp/deprecated/3_11/deploymentconfig-v1/src.rego
  policy/ocp/deprecated/3_11/imagestream-v1/src.rego
  policy/ocp/deprecated/3_11/projectrequest-v1/src.rego
  policy/ocp/deprecated/3_11/rolebinding-v1/src.rego
  policy/ocp/deprecated/3_11/route-v1/src.rego
  policy/ocp/deprecated/3_11/securitycontextconstraints-v1/src.rego
  policy/ocp/deprecated/3_11/template-v1/src.rego
  policy/ocp/deprecated/4_1/buildconfig-custom-strategy/src.rego
  policy/ocp/deprecated/4_2/authorization-openshift/src.rego
  policy/ocp/deprecated/4_2/automationbroker-v1alpha1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v2/src.rego
  policy/ocp/deprecated/4_2/operatorsources-v1/src.rego
  policy/ocp/deprecated/4_2/osb-v1/src.rego
  policy/ocp/deprecated/4_2/servicecatalog-v1beta1/src.rego
  policy/ocp/deprecated/4_3/buildconfig-jenkinspipeline-strategy/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-pvc/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-service/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/src.rego
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/src.rego
  policy/podman/history/contains-layer/src.rego
  policy/podman/images/image-size-not-greater-than/src.rego
Labels: approved, lgtm, size/XXL

#97 Added opa-profile
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/conftest.yaml
  .github/workflows/opa-profile.yaml
  .gitignore
  README.md
  TESTING.md
  _test/opa-profile.sh
  policy/ocp/bestpractices/container-image-latest/test_data/unit/list.yml
Labels: approved, lgtm, size/L

#98 Added artifacthub.yaml
  policy/artifacthub.yaml
Labels: approved, size/M

#99 Tweaked artifacthub.yaml
  policy/artifacthub.yaml
Labels: approved
