Repository redhat-cop/rego-policies, pull requests merged in 2020-06, with the labels that each got.

#13 Updated conftest download in action to be opa github due to migration
  .github/workflows/bats.yaml
  README.md
Labels: approved, lgtm, size/XS

#14 Added policy for scc's
  _test/ocp-43-deprecated-apiversions/template.yml
  _test/tests.bats
  policy/ocp-43-deprecated-apiversions.rego
Labels: approved, lgtm, size/S

#16 Fixed wrong CC group
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, lgtm, size/XS

#20 🐛 Update owners to allow me review etc 🤗
  OWNERS
Labels: approved, lgtm, size/XS

#22 Updated github action to use main confbatstest action
  .github/workflows/bats.yaml
  .github/workflows/conftest.yaml
Labels: approved, lgtm, size/M

#17 Updated tests to test against split out items
  README.md
  TESTING.md
  _test/_helpers.bash
  _test/ocp-43-deprecated-apiversions/list.yml
  _test/ocp-43-deprecated-apiversions/template.yml
  _test/tests.bats
Labels: approved, lgtm, size/L

#24 Updating naming of policies to follow a format
  README.md
  _test/deny-k8s-rolebinding-roleref/list.yml
  _test/deny-ocp42-all-deprecated-apiversions/list.yml
  _test/deny-ocp43-all-deprecated-apiversions/list.yml
  _test/deny-ocp43-all-deprecated-apiversions/template.yml
  _test/tests.bats
  policy/deny-k8s-rolebinding-roleref.rego
  policy/deny-ocp42-all-deprecated-apiversion.rego
  policy/deny-ocp43-all-deprecated-apiversions.rego
Labels: approved, lgtm, size/M

#26 Added policies for warn-k8s-deployment-conftestcombine-bestpractices
  .github/workflows/conftest.yaml
  README.md
  _test/_helpers.bash
  _test/conftest.sh
  _test/warn-k8s-deployment-conftestcombine-bestpractices/list-Deployment-PVC.yml
  _test/warn-k8s-deployment-conftestcombine-bestpractices/list-Deployment-PodDisruptionBudget.yml
  _test/warn-k8s-deployment-conftestcombine-bestpractices/list-Deployment-Service.yml
  _test/warn-k8s-deployment-conftestcombine-bestpractices/list-Deployment-ServiceAccount.yml
  policy/warn-k8s-deployment-conftestcombine-bestpractices.rego
Labels: approved, lgtm, size/L

#27 Added policies warn-k8s-namespace-conftestcombine-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-k8s-namespace-conftestcombine-bestpractices/list-Namespace-NetworkPolicy.yml
  policy/warn-k8s-namespace-conftestcombine-bestpractices.rego
Labels: approved, lgtm, size/M

#28 Added warn-k8s-service-conftestcombine-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-k8s-service-conftestcombine-bestpractices/list-Service-ServiceMonitor.yml
  policy/warn-k8s-service-conftestcombine-bestpractices.rego
Labels: approved, lgtm, size/M

#29 Added warn-k8s_ocp-all-bestpractices
  README.md
  _test/conftest.sh
  _test/deny-k8s-rolebinding-roleref/list.yml
  _test/deny-ocp42-all-deprecated-apiversions/list.yml
  _test/deny-ocp43-all-deprecated-apiversions/list.yml
  _test/deny-ocp43-all-deprecated-apiversions/template.yml
  _test/warn-k8s_ocp-all-bestpractices/list.yml
  policy/warn-k8s_ocp-all-bestpractices.rego
Labels: approved, lgtm, size/L

#30 Added warn-k8s_ocp-deployment_deploymentconfig-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-Deployment.yml
  _test/warn-k8s_ocp-deployment_deploymentconfig-bestpractices/list-DeploymentConfig.yml
  policy/warn-k8s_ocp-deployment_deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/XXL

#32 Added warn-ocp-deploymentconfig-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-ocp-deploymentconfig-bestpractices/list-DeploymentConfig.yml
  policy/warn-ocp-deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/M

#33 Added warn-podman-history-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-podman-history-bestpractices/jenkins-base.json
  _test/warn-podman-history-bestpractices/jenkins-python-mising.json
  _test/warn-podman-history-bestpractices/jenkins-python.json
  policy/warn-podman-history-bestpractices.rego
Labels: approved, lgtm, size/L

#34 Added warn-podman-images-bestpractices
  README.md
  _test/conftest.sh
  _test/warn-podman-images-bestpractices/jenkins-base.json
  policy/warn-podman-images-bestpractices.rego
Labels: approved, lgtm, size/M

#37 Added util methods for list and templates
  policy/deny-k8s-rolebinding-roleref.rego
  policy/deny-ocp42-all-deprecated-apiversion.rego
  policy/deny-ocp43-all-deprecated-apiversions.rego
  policy/utils/kubernetes.rego
  policy/utils/openshift.rego
Labels: approved, lgtm, size/M

#43 Added utils methods for checking deployment and deploymentconfig
  policy/utils/kubernetes.rego
  policy/utils/openshift.rego
  policy/warn-k8s_ocp-deployment_deploymentconfig-bestpractices.rego
  policy/warn-ocp-deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/L

#61 🖕🏻Added utils for labels duplicates
  policy/utils/labels.rego
  policy/warn-k8s_ocp-all-bestpractices.rego
  policy/warn-k8s_ocp-deployment_deploymentconfig-bestpractices.rego
Labels: approved, lgtm, size/M

#62 🕺 FIX - broken link in the md file 🕺
  TESTING.md
Labels: approved, lgtm, size/XS

#65 Added ci bagde to readme
  README.md
Labels: approved, lgtm, size/XS
