Repository redhat-cop/rego-policies, pull requests merged in 2020-08, with the labels that each got.

#100 Re-generated docs as konstraint has tweaked the dodcs command
  POLICIES.md
Labels: approved, lgtm, size/M

#102 unknown registry policy is added
  POLICIES.md
  _test/conftest-unittests.sh
  _test/gatekeeper-integrationtests.sh
  _test/opa-profile.sh
  policy/ocp/bestpractices/container-image-unknownregistries/src.rego
  policy/ocp/bestpractices/container-image-unknownregistries/test_data/integration/list.yml
  policy/ocp/bestpractices/container-image-unknownregistries/test_data/unit/list.yml
Labels: approved, lgtm, size/L

#103 Updated to gatekeeper beta12
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/XS

#104 Enabled container-resources-*-memory-greater-than tests
  _test/deploy-gatekeeper.sh
  _test/gatekeeper-integrationtests.sh
Labels: approved, lgtm, size/S

#101 adding namespace-has-resourcequota policy
  POLICIES.md
  _test/conftest-unittests.sh
  policy/combine/namespace-has-resourcequota/src.rego
  policy/combine/namespace-has-resourcequota/test_data/unit/list.yml
Labels: approved, lgtm, size/M

#106 Fixed operators.coreos.com picking up wrong kinds
  POLICIES.md
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v2/src.rego
  policy/ocp/deprecated/4_2/operatorsources-v1/src.rego
Labels: approved, lgtm, size/M

#108 Fixed deadlink in readme
  README.md
Labels: approved, lgtm, size/XS

#110 SCC RBAC implementation
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/XS

#111 Removed control-plane comment
  TESTING.md
Labels: approved, lgtm, size/XS

#119 Added new policy for insecure routes
  POLICIES.md
  TESTING.md
  _test/conftest-unittests.sh
  _test/gatekeeper-integrationtests.sh
  _test/opa-profile.sh
  policy/ocp/bestpractices/route-tls-termination-notset/src.rego
  policy/ocp/bestpractices/route-tls-termination-notset/test_data/integration/example.yml
  policy/ocp/bestpractices/route-tls-termination-notset/test_data/unit/example.yml
Labels: approved, lgtm, size/L

#116 Added inventory conftest tests
  _test/conftest-unittests.sh
  policy/ocp/requiresinventory/README.md
  policy/ocp/requiresinventory/data_inventory.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/test_data/unit/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-pvc/test_data/unit/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-service/test_data/unit/list.yml
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/test_data/unit/list.yml
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/test_data/unit/list.yml
Labels: approved, lgtm, size/L

#113 Updated conftest ci to use central
  .github/workflows/opa-profile.yaml
Labels: approved, lgtm, size/XS

#114 Upgraded to gatekeeper 3.1.0 rc1
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/XS

#118 Added emit admission events to gatekeeper
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/XS
