Repository redhat-cop/rego-policies, pull requests merged in 2021-07, with the labels that each got.

#159 added kind support to deploy gatekeeper and crds
  .github/workflows/conftest.yaml
Labels: approved, lgtm, size/S

#163 upgraded kind due to networking issue
  .github/workflows/conftest.yaml
Labels: approved, lgtm, size/XS

#164 updated template apiVersion for test resources to be fully qualified
  _test/resources/namespace-under-test.yml
  _test/resources/prerequisite-bestpractices.yml
  _test/resources/prerequisite-requiresinventory.yml
  policy/ocp/bestpractices/_all-namespaces/test_data/integration/all.yml
Labels: approved, lgtm, size/XS

#165 added testing best practices via kind
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/conftest.yaml
  TESTING.md
  _test/gatekeeper-k8s-integrationtests.sh
  _test/prow.sh
Labels: approved, lgtm, size/L

#167 container-secret-mounted-envs message fix
  policy/ocp/bestpractices/container-secret-mounted-envs/src.rego
Labels: approved, lgtm, size/XS

#168 fixed ci failing due to #167
  POLICIES.md
  _test/conftest-unittests.sh
Labels: approved, lgtm, size/XS
