Repository redhat-cop/rego-policies, pull requests merged in 2021-03, with the labels that each got.

#143 moved comments block to top of file due to konstraint change
  POLICIES.md
  policy/combine/namespace-has-networkpolicy/src.rego
  policy/combine/namespace-has-resourcequota/src.rego
  policy/ocp/bestpractices/common-k8s-labels-notset/src.rego
  policy/ocp/bestpractices/container-env-maxmemory-notset/src.rego
  policy/ocp/bestpractices/container-image-latest/src.rego
  policy/ocp/bestpractices/container-image-unknownregistries/src.rego
  policy/ocp/bestpractices/container-java-xmx-set/src.rego
  policy/ocp/bestpractices/container-labelkey-inconsistent/src.rego
  policy/ocp/bestpractices/container-liveness-readinessprobe-equal/src.rego
  policy/ocp/bestpractices/container-livenessprobe-notset/src.rego
  policy/ocp/bestpractices/container-readinessprobe-notset/src.rego
  policy/ocp/bestpractices/container-resources-limits-cpu-set/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-notset/src.rego
  policy/ocp/bestpractices/container-resources-memoryunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-cpuunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-secret-mounted-envs/src.rego
  policy/ocp/bestpractices/container-volumemount-inconsistent-path/src.rego
  policy/ocp/bestpractices/container-volumemount-missing/src.rego
  policy/ocp/bestpractices/deploymentconfig-triggers-notset/src.rego
  policy/ocp/bestpractices/pod-antiaffinity-notset/src.rego
  policy/ocp/bestpractices/pod-hostnetwork/src.rego
  policy/ocp/bestpractices/pod-replicas-below-one/src.rego
  policy/ocp/bestpractices/pod-replicas-not-odd/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-apigroup-notset/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-kind-notset/src.rego
  policy/ocp/bestpractices/route-tls-termination-notset/src.rego
  policy/ocp/deprecated/3_11/buildconfig-v1/src.rego
  policy/ocp/deprecated/3_11/deploymentconfig-v1/src.rego
  policy/ocp/deprecated/3_11/imagestream-v1/src.rego
  policy/ocp/deprecated/3_11/projectrequest-v1/src.rego
  policy/ocp/deprecated/3_11/rolebinding-v1/src.rego
  policy/ocp/deprecated/3_11/route-v1/src.rego
  policy/ocp/deprecated/3_11/securitycontextconstraints-v1/src.rego
  policy/ocp/deprecated/3_11/template-v1/src.rego
  policy/ocp/deprecated/4_1/buildconfig-custom-strategy/src.rego
  policy/ocp/deprecated/4_2/authorization-openshift/src.rego
  policy/ocp/deprecated/4_2/automationbroker-v1alpha1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v2/src.rego
  policy/ocp/deprecated/4_2/operatorsources-v1/src.rego
  policy/ocp/deprecated/4_2/osb-v1/src.rego
  policy/ocp/deprecated/4_2/servicecatalog-v1beta1/src.rego
  policy/ocp/deprecated/4_3/buildconfig-jenkinspipeline-strategy/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-pvc/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-service/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/src.rego
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/src.rego
  policy/podman/history/contains-layer/src.rego
  policy/podman/images/image-size-not-greater-than/src.rego
Labels: approved, lgtm, size/L

#142 added missing opa eval for pod anti-affinity
  _test/opa-profile.sh
Labels: approved, lgtm, size/S

#145 bumped gatekeeper version to latest
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/XS

#147 added --exempt-namespace for all core namespaces (i.e.: openshift / kube)
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/S

#149 Added wrapper script to make life easier to deploy via prow
  _test/deploy-gatekeeper.sh
  _test/prow.sh
Labels: approved, lgtm, size/M

#152 added @skip-constraint to policies which cannot be deployed against gatekeeper
  _test/deploy-gatekeeper.sh
  policy/combine/namespace-has-networkpolicy/src.rego
  policy/combine/namespace-has-resourcequota/src.rego
  policy/ocp/bestpractices/deploymentconfig-triggers-notset/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-apigroup-notset/src.rego
  policy/ocp/bestpractices/rolebinding-roleref-kind-notset/src.rego
  policy/ocp/deprecated/3_11/buildconfig-v1/src.rego
  policy/ocp/deprecated/3_11/deploymentconfig-v1/src.rego
  policy/ocp/deprecated/3_11/imagestream-v1/src.rego
  policy/ocp/deprecated/3_11/projectrequest-v1/src.rego
  policy/ocp/deprecated/3_11/rolebinding-v1/src.rego
  policy/ocp/deprecated/3_11/route-v1/src.rego
  policy/ocp/deprecated/3_11/securitycontextconstraints-v1/src.rego
  policy/ocp/deprecated/3_11/template-v1/src.rego
  policy/ocp/deprecated/4_1/buildconfig-custom-strategy/src.rego
  policy/ocp/deprecated/4_2/authorization-openshift/src.rego
  policy/ocp/deprecated/4_2/automationbroker-v1alpha1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v1/src.rego
  policy/ocp/deprecated/4_2/catalogsourceconfigs-v2/src.rego
  policy/ocp/deprecated/4_2/operatorsources-v1/src.rego
  policy/ocp/deprecated/4_2/osb-v1/src.rego
  policy/ocp/deprecated/4_2/servicecatalog-v1beta1/src.rego
  policy/ocp/deprecated/4_3/buildconfig-jenkinspipeline-strategy/src.rego
  policy/podman/history/contains-layer/src.rego
  policy/podman/images/image-size-not-greater-than/src.rego
Labels: approved, lgtm, size/S

#151 added policy active to all other gatekeeper policies
  POLICIES.md
  policy/ocp/bestpractices/container-env-maxmemory-notset/src.rego
  policy/ocp/bestpractices/container-image-latest/src.rego
  policy/ocp/bestpractices/container-image-unknownregistries/src.rego
  policy/ocp/bestpractices/container-java-xmx-set/src.rego
  policy/ocp/bestpractices/container-labelkey-inconsistent/src.rego
  policy/ocp/bestpractices/container-liveness-readinessprobe-equal/src.rego
  policy/ocp/bestpractices/container-livenessprobe-notset/src.rego
  policy/ocp/bestpractices/container-readinessprobe-notset/src.rego
  policy/ocp/bestpractices/container-resources-limits-cpu-set/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-resources-limits-memory-notset/src.rego
  policy/ocp/bestpractices/container-resources-memoryunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-cpuunit-incorrect/src.rego
  policy/ocp/bestpractices/container-resources-requests-memory-greater-than/src.rego
  policy/ocp/bestpractices/container-secret-mounted-envs/src.rego
  policy/ocp/bestpractices/container-volumemount-inconsistent-path/src.rego
  policy/ocp/bestpractices/container-volumemount-missing/src.rego
  policy/ocp/bestpractices/pod-antiaffinity-notset/src.rego
  policy/ocp/bestpractices/pod-hostnetwork/src.rego
  policy/ocp/bestpractices/pod-replicas-below-one/src.rego
  policy/ocp/bestpractices/pod-replicas-not-odd/src.rego
  policy/ocp/bestpractices/route-tls-termination-notset/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-poddisruptionbudget/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-pvc/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-service/src.rego
  policy/ocp/requiresinventory/deployment-has-matching-serviceaccount/src.rego
  policy/ocp/requiresinventory/service-has-matching-servicemonitor/src.rego
Labels: approved, lgtm, size/M

#153 added example and docs to describe operator deployment
  gatekeeper/operator/README.md
  gatekeeper/operator/gatekeeper-cr-example.yaml
Labels: approved, lgtm, size/M

#150 added checking to opa-profile to make sure correct policy is run
  _test/opa-profile.sh
Labels: approved, lgtm, size/XL

#140 added dc trigger containers name is in containers list
  POLICIES.md
  _test/conftest-unittests.sh
  _test/gatekeeper-integrationtests.sh
  _test/opa-profile.sh
  policy/ocp/bestpractices/deploymentconfig-triggers-containername/src.rego
  policy/ocp/bestpractices/deploymentconfig-triggers-containername/test_data/integration/list.yml
  policy/ocp/bestpractices/deploymentconfig-triggers-containername/test_data/unit/example.yml
Labels: approved, lgtm, size/L

#154 Add cleanup option and ignore missing CRDs
  _test/deploy-gatekeeper.sh
Labels: approved, lgtm, size/S
